"""add price col to stick

Revision ID: 0d6e3e1d9c10
Revises: a30d034e8736
Create Date: 2025-06-03 01:02:29.019392

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d6e3e1d9c10"
down_revision: Union[str, None] = "a30d034e8736"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stick", sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stick", "price")
    # ### end Alembic commands ###
