"""add discount to stick

Revision ID: 0eb1cf612c4f
Revises: 0d6e3e1d9c10
Create Date: 2025-06-03 01:12:15.075605

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0eb1cf612c4f"
down_revision: Union[str, None] = "0d6e3e1d9c10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stick", sa.Column("discount", sa.Numeric(precision=4, scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stick", "discount")
    # ### end Alembic commands ###
