"""add ships_to col to Website

Revision ID: 12de3682b041
Revises: 51ef4ffc3418
Create Date: 2025-05-07 16:38:51.928507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '12de3682b041'
down_revision: Union[str, None] = '51ef4ffc3418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website', sa.Column('ships_to', sqlmodel.sql.sqltypes.AutoString(length=255), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website', 'ships_to')
    # ### end Alembic commands ###
