"""add price drop and hist low col to stick

Revision ID: 1ad319454ebb
Revises: 83b759cc675f
Create Date: 2025-06-03 16:48:04.182844

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ad319454ebb"
down_revision: Union[str, None] = "83b759cc675f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stick", sa.Column("price_drop", sa.Boolean(), nullable=False))
    op.add_column("stick", sa.Column("historical_low", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stick", "historical_low")
    op.drop_column("stick", "price_drop")
    # ### end Alembic commands ###
