"""add stickurl table

Revision ID: 2e488b97bb70
Revises: 572c05d99f72
Create Date: 2025-06-08 20:15:59.969777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e488b97bb70'
down_revision: Union[str, None] = '572c05d99f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stickurl',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('spider_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stick_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stick_id'], ['stick.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stickurl_spider_name'), 'stickurl', ['spider_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stickurl_spider_name'), table_name='stickurl')
    op.drop_table('stickurl')
    # ### end Alembic commands ###
