"""add currency col to deal

Revision ID: 48495a57707b
Revises: e0b78f3b6767
Create Date: 2025-06-01 23:55:54.833359

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48495a57707b"
down_revision: Union[str, None] = "e0b78f3b6767"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deal",
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deal", "currency")
    # ### end Alembic commands ###
