"""add freq col to useralert

Revision ID: 492edcd737c0
Revises: ca0207d67f05
Create Date: 2025-05-04 20:21:31.662003

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "492edcd737c0"
down_revision: Union[str, None] = "ca0207d67f05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "useralert",
        sa.Column(
            "frequency",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
            server_default="weekly",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("useralert", "frequency")
    # ### end Alembic commands ###
