"""make website url unique

Revision ID: 49a28d6823cb
Revises: 060c6ea12c2f
Create Date: 2025-02-18 02:27:28.124546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '49a28d6823cb'
down_revision: Union[str, None] = '060c6ea12c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'website', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'website', type_='unique')
    # ### end Alembic commands ###
