"""add slug col to stick

Revision ID: 572c05d99f72
Revises: e6829b94d607
Create Date: 2025-06-08 19:27:32.176923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '572c05d99f72'
down_revision: Union[str, None] = 'e6829b94d607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stick', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), server_default='none', nullable=False))
    op.alter_column('website', 'country',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website', 'country',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=3),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('stick', 'slug')
    # ### end Alembic commands ###
