"""add logo col to website

Revision ID: 5eccd5279ba3
Revises: 1ad319454ebb
Create Date: 2025-06-04 15:32:07.904585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5eccd5279ba3'
down_revision: Union[str, None] = '1ad319454ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website', sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website', 'logo')
    # ### end Alembic commands ###
