"""remove frequency

Revision ID: 8ad5761fcb3d
Revises: c8c57939c3bf
Create Date: 2025-05-08 16:55:21.475694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ad5761fcb3d'
down_revision: Union[str, None] = 'c8c57939c3bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useralert', 'frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useralert', sa.Column('frequency', sa.VARCHAR(length=20), server_default=sa.text("'weekly'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
