"""add flex_options curve_options to stick

Revision ID: 93a91ce69655
Revises: 2e488b97bb70
Create Date: 2025-06-08 21:33:48.282251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93a91ce69655'
down_revision: Union[str, None] = '2e488b97bb70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stick', sa.Column('flex_options', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('stick', sa.Column('curve_options', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stick', 'curve_options')
    op.drop_column('stick', 'flex_options')
    # ### end Alembic commands ###
