"""price url unique constraint

Revision ID: 9b6ed1f0deb0
Revises: 49a28d6823cb
Create Date: 2025-02-18 03:05:55.142543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b6ed1f0deb0'
down_revision: Union[str, None] = '49a28d6823cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal',
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('discount', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('website_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='deal_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], name='deal_website_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='deal_pkey')
    )
    # ### end Alembic commands ###
