"""add stickimage table

Revision ID: a30d034e8736
Revises: 48495a57707b
Create Date: 2025-06-02 18:41:48.786394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a30d034e8736'
down_revision: Union[str, None] = '48495a57707b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stickimage',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stick_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stick_id'], ['stick.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stickimage')
    # ### end Alembic commands ###
