"""add stick tracking

Revision ID: a7548c83b4b4
Revises: cb224b8ea314
Create Date: 2025-05-30 22:27:40.395954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a7548c83b4b4'
down_revision: Union[str, None] = 'cb224b8ea314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stick',
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('line', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('handedness', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('flex', sa.Integer(), nullable=False),
    sa.Column('curve', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stick_model_name'), 'stick', ['model_name'], unique=False)
    op.create_table('stickprice',
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('stick_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stick_id'], ['stick.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stickprice')
    op.drop_index(op.f('ix_stick_model_name'), table_name='stick')
    op.drop_table('stick')
    # ### end Alembic commands ###
