"""add deals.views column

Revision ID: b2af6962ea9f
Revises: c8078a10c411
Create Date: 2025-04-17 23:16:14.433874

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2af6962ea9f"
down_revision: Union[str, None] = "c8078a10c411"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deal",
        sa.Column("views", sa.Integer(), nullable=False, default=0, server_default="0"),
    )
    op.drop_constraint(
        "tagproductlink_tag_id_fkey", "tagproductlink", type_="foreignkey"
    )
    op.drop_constraint(
        "tagproductlink_product_id_fkey", "tagproductlink", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "tagproductlink", "tag", ["tag_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "tagproductlink", "product", ["product_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tagproductlink", type_="foreignkey")
    op.drop_constraint(None, "tagproductlink", type_="foreignkey")
    op.create_foreign_key(
        "tagproductlink_product_id_fkey",
        "tagproductlink",
        "product",
        ["product_id"],
        ["id"],
    )
    op.create_foreign_key(
        "tagproductlink_tag_id_fkey", "tagproductlink", "tag", ["tag_id"], ["id"]
    )
    op.drop_column("deal", "views")
    # ### end Alembic commands ###
