"""CASCADE delete UserAlert

Revision ID: c8c57939c3bf
Revises: ed650b97e668
Create Date: 2025-05-07 17:14:34.442932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c8c57939c3bf'
down_revision: Union[str, None] = 'ed650b97e668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('useralert_user_id_fkey', 'useralert', type_='foreignkey')
    op.create_foreign_key(None, 'useralert', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'useralert', type_='foreignkey')
    op.create_foreign_key('useralert_user_id_fkey', 'useralert', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
