"""add country col to User

Revision ID: df8a0d53d42d
Revises: 8ad5761fcb3d
Create Date: 2025-05-08 20:42:10.444646

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df8a0d53d42d"
down_revision: Union[str, None] = "8ad5761fcb3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "country",
            sqlmodel.sql.sqltypes.AutoString(length=5),
            default="US",
            server_default="US",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "country")
    # ### end Alembic commands ###
