"""add msrp col to Stick

Revision ID: e0b78f3b6767
Revises: e25b810e5077
Create Date: 2025-06-01 04:41:19.627368

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0b78f3b6767"
down_revision: Union[str, None] = "e25b810e5077"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stick", sa.Column("msrp", sa.Numeric(precision=10, scale=2), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stick", "msrp")
    # ### end Alembic commands ###
