"""add description kickpoint col to sticks

Revision ID: e25b810e5077
Revises: a7548c83b4b4
Create Date: 2025-05-31 00:21:48.085958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e25b810e5077'
down_revision: Union[str, None] = 'a7548c83b4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stick', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('stick', sa.Column('kickpoint', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stick', 'kickpoint')
    op.drop_column('stick', 'description')
    # ### end Alembic commands ###
