"""add exchangeRate table

Revision ID: e6829b94d607
Revises: 5eccd5279ba3
Create Date: 2025-06-05 02:12:18.228830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e6829b94d607'
down_revision: Union[str, None] = '5eccd5279ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchangerate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('target_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchangerate')
    # ### end Alembic commands ###
