"""add size,brand,tag col to UserAlert

Revision ID: ed650b97e668
Revises: 12de3682b041
Create Date: 2025-05-07 17:13:27.718208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed650b97e668'
down_revision: Union[str, None] = '12de3682b041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useralert', sa.Column('size', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('useralert', sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('useralert', sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('useralert', 'keyword',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('useralert', 'keyword',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('useralert', 'tag')
    op.drop_column('useralert', 'brand')
    op.drop_column('useralert', 'size')
    # ### end Alembic commands ###
