"""discount precision

Revision ID: 2b3561b1f754
Revises: d435ed5f497b
Create Date: 2025-02-14 00:32:07.169879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3561b1f754'
down_revision: Union[str, None] = 'd435ed5f497b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deals', 'discount',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               type_=sa.DECIMAL(precision=4, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deals', 'discount',
               existing_type=sa.DECIMAL(precision=4, scale=2),
               type_=sa.NUMERIC(precision=2, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
